CREATE TABLE IF NOT EXISTS "anthropometric_assessments" (
  "id" varchar PRIMARY KEY NOT NULL,
  "patient_id" varchar NOT NULL REFERENCES "patients"("id") ON DELETE CASCADE,
  "nutritionist_id" varchar NOT NULL REFERENCES "users"("id"),
  "title" varchar NOT NULL,
  "circum_neck" real,
  "circum_shoulders" real,
  "circum_chest" real,
  "circum_waist" real,
  "circum_abdomen" real,
  "circum_hip" real,
  "circum_right_arm" real,
  "circum_left_arm" real,
  "circum_right_thigh" real,
  "circum_left_thigh" real,
  "circum_right_calf" real,
  "circum_left_calf" real,
  "fold_biceps" real,
  "fold_triceps" real,
  "fold_subscapular" real,
  "fold_suprailiac" real,
  "created_at" timestamp DEFAULT now(),
  "updated_at" timestamp DEFAULT now()
);
